version: '3'

services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:10.14
    environment: 
      - POSTGRES_DB=yjdb
      - POSTGRES_PASSWORD=lorem
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - default
networks:
  default: